theme: jekyll-theme-minimal
title: Jonathan Sam
description: Sr Professional, Climate Change Scientist
  CoreLogic -- Oakland, CA
  
  PhD Candidate, Environmental Systems
  University of California, Merced
